<?php

use Illuminate\Support\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // 今の時刻を取得し、
        $best_before_date = Carbon::now();
        // それを1週間後にする
        $best_before_date->addDays(7);

        // 今の時刻を取得し、
        $expired_date = Carbon::now();
        // それを1週間前にする
        $expired_date->subDays(7);

        DB::table('products')->insert([
            [
                'seller_id' => 1,
                'user_id' => null,
                'category_id' => 1,
                'company_id' => 1,
                'prefecture' => '北海道',
                'product_name' => '和風ツナマヨおにぎり',
                'description' => '',
                'original_price' => 110,
                'price' => 60,
                'best_defore_date' => $best_before_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/WJNNdR5aR7C06Dpl41cGS7wcZXDXrXBdq7MCDNYh.jpg',
                'is_expired' => 0,
                'is_sold' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 1,
                'user_id' => null,
                'category_id' => 2,
                'company_id' => 1,
                'prefecture' => '北海道',
                'product_name' => 'ボリューム満点からあげ弁当',
                'description' => '',
                'original_price' => 445,
                'price' => 220,
                'best_defore_date' => $best_before_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/4ckHNvCmo44iw04CrWu9tdeZ1ykWXmFVpcdFpA0C.jpg',
                'is_expired' => 0,
                'is_sold' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 1,
                'user_id' => null,
                'category_id' => 3,
                'company_id' => 1,
                'prefecture' => '北海道',
                'product_name' => '旬のお魚にぎり寿司セット',
                'description' => '',
                'original_price' => 600,
                'price' => 300,
                'best_defore_date' => $best_before_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/n3IXKVzSAd9WQ9YOYr6smVHYDz4ZaYyDM1kRpnS3.jpg',
                'is_expired' => 0,
                'is_sold' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 1,
                'user_id' => null,
                'category_id' => 4,
                'company_id' => 1,
                'prefecture' => '北海道',
                'product_name' => 'ハムたまご＆野菜ミックス',
                'description' => '',
                'original_price' => 290,
                'price' => 180,
                'best_defore_date' => $best_before_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/1kegy0ElzuXgc7aSgmZXYPHGQkgXCUr3Qqb5nMur.jpg',
                'is_expired' => 0,
                'is_sold' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 1,
                'user_id' => null,
                'category_id' => 5,
                'company_id' => 1,
                'prefecture' => '北海道',
                'product_name' => 'しっとりシナモンロール 2個入り',
                'description' => 'テキストテキストテキストテキストテキスト',
                'original_price' => 160,
                'price' => 80,
                'best_defore_date' => $best_before_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/BEAlMedtmb6bZtl2d607rewlhP9XTeH4nVDjvbjG.jpg',
                'is_expired' => 0,
                'is_sold' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 1,
                'user_id' => null,
                'category_id' => 6,
                'company_id' => 1,
                'prefecture' => '北海道',
                'product_name' => 'のどごしちゅるっとうどん',
                'description' => 'テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト',
                'original_price' => 480,
                'price' => 240,
                'best_defore_date' => $best_before_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/tgDRqQufQnwaGUibhSX2wOg7WFNt1P6bEYtvkm0l.jpg',
                'is_expired' => 0,
                'is_sold' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 1,
                'user_id' => null,
                'category_id' => 7,
                'company_id' => 1,
                'prefecture' => '北海道',
                'product_name' => '大盛 シーフードぺぺロンチーノ',
                'description' => 'テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト',
                'original_price' => 500,
                'price' => 250,
                'best_defore_date' => $best_before_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/Uuiwgd6geaovQVUgIi3cpAUiFh3LK1mCUkIJMyN0.jpg',
                'is_expired' => 0,
                'is_sold' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 1,
                'user_id' => null,
                'category_id' => 8,
                'company_id' => 1,
                'prefecture' => '北海道',
                'product_name' => '5種類のデリサラダ',
                'description' => 'テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト',
                'original_price' => 280,
                'price' => 140,
                'best_defore_date' => $best_before_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/PNFyt4at6ckpRk2IybT2DK3LhpkUSCVlQq8pTzrz.jpg',
                'is_expired' => 0,
                'is_sold' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 1,
                'user_id' => null,
                'category_id' => 9,
                'company_id' => 1,
                'prefecture' => '北海道',
                'product_name' => '本格イタリアンティラミス',
                'description' => 'テキストテキストテキストテキストテキストテキストテキスト',
                'original_price' => 340,
                'price' => 170,
                'best_defore_date' => $best_before_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/HXab44VYjVutPLMi1RkOqwrtoqUbEsqm7GbZ5P7h.jpg',
                'is_expired' => 0,
                'is_sold' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 1,
                'user_id' => null,
                'category_id' => 10,
                'company_id' => 1,
                'prefecture' => '北海道',
                'product_name' => 'コンソメ風味のポテトチップス',
                'description' => 'テキストテキストテキストテキストテキストテキストテキストテキスト',
                'original_price' => 180,
                'price' => 90,
                'best_defore_date' => $best_before_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/6OoxTziqa5VuhiSDoN3RdPHPXUbad98kNx7JhHBu.jpg',
                'is_expired' => 0,
                'is_sold' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 1,
                'user_id' => null,
                'category_id' => 10,
                'company_id' => 1,
                'prefecture' => '北海道',
                'product_name' => 'コンソメ風味のポテトチップス',
                'description' => 'テキストテキストテキストテキストテキストテキストテキストテキスト',
                'original_price' => 180,
                'price' => 90,
                'best_defore_date' => $best_before_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/6OoxTziqa5VuhiSDoN3RdPHPXUbad98kNx7JhHBu.jpg',
                'is_expired' => 0,
                'is_sold' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // 2番目のテスト店舗の商品。全て売り切れ。商品説明なし。
            [
                'seller_id' => 2,
                'user_id' => 1,
                'category_id' => 1,
                'company_id' => 2,
                'prefecture' => '青森県',
                'product_name' => '和風ツナマヨおにぎり',
                'description' => '',
                'original_price' => 110,
                'price' => 60,
                'best_defore_date' => $best_before_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/WJNNdR5aR7C06Dpl41cGS7wcZXDXrXBdq7MCDNYh.jpg',
                'is_expired' => 0,
                'is_sold' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 2,
                'user_id' => 1,
                'category_id' => 2,
                'company_id' => 2,
                'prefecture' => '青森県',
                'product_name' => 'ボリューム満点からあげ弁当',
                'description' => '',
                'original_price' => 445,
                'price' => 220,
                'best_defore_date' => $best_before_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/4ckHNvCmo44iw04CrWu9tdeZ1ykWXmFVpcdFpA0C.jpg',
                'is_expired' => 0,
                'is_sold' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 2,
                'user_id' => 1,
                'category_id' => 3,
                'company_id' => 2,
                'prefecture' => '青森県',
                'product_name' => '旬のお魚にぎり寿司セット',
                'description' => '',
                'original_price' => 600,
                'price' => 300,
                'best_defore_date' => $best_before_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/n3IXKVzSAd9WQ9YOYr6smVHYDz4ZaYyDM1kRpnS3.jpg',
                'is_expired' => 0,
                'is_sold' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 2,
                'user_id' => 1,
                'category_id' => 4,
                'company_id' => 2,
                'prefecture' => '青森県',
                'product_name' => 'ハムたまご＆野菜ミックス',
                'description' => '',
                'original_price' => 290,
                'price' => 180,
                'best_defore_date' => $best_before_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/1kegy0ElzuXgc7aSgmZXYPHGQkgXCUr3Qqb5nMur.jpg',
                'is_expired' => 0,
                'is_sold' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 2,
                'user_id' => 1,
                'category_id' => 5,
                'company_id' => 2,
                'prefecture' => '青森県',
                'product_name' => 'しっとりシナモンロール 2個入り',
                'description' => '',
                'original_price' => 160,
                'price' => 80,
                'best_defore_date' => $best_before_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/BEAlMedtmb6bZtl2d607rewlhP9XTeH4nVDjvbjG.jpg',
                'is_expired' => 0,
                'is_sold' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 2,
                'user_id' => 2,
                'category_id' => 6,
                'company_id' => 2,
                'prefecture' => '青森県',
                'product_name' => 'のどごしちゅるっとうどん',
                'description' => '',
                'original_price' => 480,
                'price' => 240,
                'best_defore_date' => $best_before_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/tgDRqQufQnwaGUibhSX2wOg7WFNt1P6bEYtvkm0l.jpg',
                'is_expired' => 0,
                'is_sold' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 2,
                'user_id' => 2,
                'category_id' => 7,
                'company_id' => 2,
                'prefecture' => '青森県',
                'product_name' => '大盛 シーフードぺぺロンチーノ',
                'description' => '',
                'original_price' => 500,
                'price' => 250,
                'best_defore_date' => $best_before_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/Uuiwgd6geaovQVUgIi3cpAUiFh3LK1mCUkIJMyN0.jpg',
                'is_expired' => 0,
                'is_sold' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 2,
                'user_id' => 2,
                'category_id' => 8,
                'company_id' => 2,
                'prefecture' => '青森県',
                'product_name' => '5種類のデリサラダ',
                'description' => '',
                'original_price' => 280,
                'price' => 140,
                'best_defore_date' => $best_before_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/PNFyt4at6ckpRk2IybT2DK3LhpkUSCVlQq8pTzrz.jpg',
                'is_expired' => 0,
                'is_sold' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 2,
                'user_id' => 2,
                'category_id' => 9,
                'company_id' => 2,
                'prefecture' => '青森県',
                'product_name' => '本格イタリアンティラミス',
                'description' => '',
                'original_price' => 340,
                'price' => 170,
                'best_defore_date' => $best_before_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/HXab44VYjVutPLMi1RkOqwrtoqUbEsqm7GbZ5P7h.jpg',
                'is_expired' => 0,
                'is_sold' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 2,
                'user_id' => 2,
                'category_id' => 10,
                'company_id' => 2,
                'prefecture' => '青森県',
                'product_name' => 'コンソメ風味のポテトチップス',
                'description' => '',
                'original_price' => 180,
                'price' => 90,
                'best_defore_date' => $best_before_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/6OoxTziqa5VuhiSDoN3RdPHPXUbad98kNx7JhHBu.jpg',
                'is_expired' => 0,
                'is_sold' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            // 3番目の店舗の商品。全て賞味期限切れ。
            [
                'seller_id' => 3,
                'user_id' => null,
                'category_id' => 1,
                'company_id' => 3,
                'prefecture' => '岩手県',
                'product_name' => '和風ツナマヨおにぎり',
                'description' => 'テキストテキストテキストテキストテキストテキスト',
                'original_price' => 110,
                'price' => 60,
                'best_defore_date' => $expired_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/WJNNdR5aR7C06Dpl41cGS7wcZXDXrXBdq7MCDNYh.jpg',
                'is_expired' => 1,
                'is_sold' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 3,
                'user_id' => null,
                'category_id' => 2,
                'company_id' => 3,
                'prefecture' => '岩手県',
                'product_name' => 'ボリューム満点からあげ弁当',
                'description' => '',
                'original_price' => 445,
                'price' => 220,
                'best_defore_date' => $expired_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/4ckHNvCmo44iw04CrWu9tdeZ1ykWXmFVpcdFpA0C.jpg',
                'is_expired' => 1,
                'is_sold' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 3,
                'user_id' => null,
                'category_id' => 3,
                'company_id' => 3,
                'prefecture' => '岩手県',
                'product_name' => '旬のお魚にぎり寿司セット',
                'description' => 'テキストテキストテキストテキストテキストテキスト',
                'original_price' => 600,
                'price' => 300,
                'best_defore_date' => $expired_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/n3IXKVzSAd9WQ9YOYr6smVHYDz4ZaYyDM1kRpnS3.jpg',
                'is_expired' => 1,
                'is_sold' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 3,
                'user_id' => null,
                'category_id' => 4,
                'company_id' => 3,
                'prefecture' => '岩手県',
                'product_name' => 'ハムたまご＆野菜ミックス',
                'description' => '',
                'original_price' => 290,
                'price' => 180,
                'best_defore_date' => $expired_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/1kegy0ElzuXgc7aSgmZXYPHGQkgXCUr3Qqb5nMur.jpg',
                'is_expired' => 1,
                'is_sold' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 3,
                'user_id' => null,
                'category_id' => 5,
                'company_id' => 3,
                'prefecture' => '岩手県',
                'product_name' => 'しっとりシナモンロール 2個入り',
                'description' => 'テキストテキストテキストテキストテキストテキスト',
                'original_price' => 160,
                'price' => 80,
                'best_defore_date' => $expired_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/BEAlMedtmb6bZtl2d607rewlhP9XTeH4nVDjvbjG.jpg',
                'is_expired' => 1,
                'is_sold' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 3,
                'user_id' => null,
                'category_id' => 6,
                'company_id' => 3,
                'prefecture' => '岩手県',
                'product_name' => 'のどごしちゅるっとうどん',
                'description' => '',
                'original_price' => 480,
                'price' => 240,
                'best_defore_date' => $expired_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/tgDRqQufQnwaGUibhSX2wOg7WFNt1P6bEYtvkm0l.jpg',
                'is_expired' => 1,
                'is_sold' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 3,
                'user_id' => null,
                'category_id' => 7,
                'company_id' => 3,
                'prefecture' => '岩手県',
                'product_name' => '大盛 シーフードぺぺロンチーノ',
                'description' => '',
                'original_price' => 500,
                'price' => 250,
                'best_defore_date' => $expired_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/Uuiwgd6geaovQVUgIi3cpAUiFh3LK1mCUkIJMyN0.jpg',
                'is_expired' => 1,
                'is_sold' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 3,
                'user_id' => null,
                'category_id' => 8,
                'company_id' => 3,
                'prefecture' => '岩手県',
                'product_name' => '5種類のデリサラダ',
                'description' => '',
                'original_price' => 280,
                'price' => 140,
                'best_defore_date' => $expired_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/PNFyt4at6ckpRk2IybT2DK3LhpkUSCVlQq8pTzrz.jpg',
                'is_expired' => 1,
                'is_sold' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 3,
                'user_id' => null,
                'category_id' => 9,
                'company_id' => 3,
                'prefecture' => '岩手県',
                'product_name' => '本格イタリアンティラミス',
                'description' => '',
                'original_price' => 340,
                'price' => 170,
                'best_defore_date' => $expired_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/HXab44VYjVutPLMi1RkOqwrtoqUbEsqm7GbZ5P7h.jpg',
                'is_expired' => 1,
                'is_sold' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 3,
                'user_id' => null,
                'category_id' => 10,
                'company_id' => 3,
                'prefecture' => '岩手県',
                'product_name' => 'コンソメ風味のポテトチップス',
                'description' => '',
                'original_price' => 180,
                'price' => 90,
                'best_defore_date' => $expired_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/6OoxTziqa5VuhiSDoN3RdPHPXUbad98kNx7JhHBu.jpg',
                'is_expired' => 1,
                'is_sold' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'seller_id' => 3,
                'user_id' => null,
                'category_id' => 10,
                'company_id' => 3,
                'prefecture' => '岩手県',
                'product_name' => 'コンソメ風味のポテトチップス',
                'description' => '',
                'original_price' => 180,
                'price' => 90,
                'best_defore_date' => $expired_date,
                'product_img_file_path' => 'https://haiki-share-backet.s3.ap-northeast-1.amazonaws.com/product-images/6OoxTziqa5VuhiSDoN3RdPHPXUbad98kNx7JhHBu.jpg',
                'is_expired' => 1,
                'is_sold' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
